---
# kubectl create serviceaccount webapp-sa
# https://learn.hashicorp.com/tutorials/vault/kubernetes-secret-store-driver
#
# helm install vault hashicorp/vault --set "global.openshift=true" --set "server.dev.enabled=true" --set "server.dev.devroottoken=root" --set "injector.enabled=false" --set "csi.enabled=false"
# andi@T480:~/Downloads$ oc exec -it vault-0 -- sh
# / $ vault kv put secret/test password="123"
#
# Get the issuer:
# andi@T480:~/Downloads$ kubectl proxy
# andi@T480:~/Downloads$ curl --silent http://127.0.0.1:8001/.well-known/openid-configuration | jq -r .issuer
# https://kubernetes.default.svc
#
# vault write auth/kubernetes/config issuer="https://kubernetes.default.svc" token_reviewer_jwt="$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" kubernetes_host="https://$KUBERNETES_PORT_443_TCP_ADDR:443" kubernetes_ca_cert=@/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
#
# vault policy write internal-app - <<EOF
# path "secret/*" {
#   capabilities = ["read"]
# }
# EOF
#
# vault write auth/kubernetes/role/test bound_service_account_names=webapp-sa bound_service_account_namespaces=csi-vault-test-app policies=internal-app ttl=20m
#
# Test:
# andi@T480:~/Downloads$ oc exec -it webapp -- cat /mnt/secrets-store/test-secret-from-vault
# 123

kind: Pod
apiVersion: v1
metadata:
  name: webapp
spec:
  serviceAccountName: webapp-sa
  containers:
  - image: jweissig/app:0.0.1
    name: webapp
    volumeMounts:
    - name: secrets-store-inline
      mountPath: "/mnt/secrets-store"
      readOnly: true
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "vault-creds"
